/**
 * Phase 1.5.1: surface-form -> lemma map, e.g. {"hunters": "hunter"}.
 *
 * The pipeline lemmatizes vocabulary at build time (hunters -> hunter), but a
 * player typing a natural inflection ("hunters") was getting a false
 * "not in dictionary" because the client did a literal string lookup against
 * the lemma-only rank table. This map, generated by
 * pipeline/build_vocabulary.py from the exact same spaCy pass that built
 * vocabulary.txt, lets the client translate a typed surface form to its
 * lemma before rank lookup, with zero risk of drifting from the pipeline's
 * own lemmatization (see resolveGuessKey in gameReducer.ts's submitGuess).
 */
export type FormMap = Record<string, string>;

/**
 * Fetches forms.json. Failure degrades gracefully to an empty map (exact
 * lemma-only lookup, the pre-fix behavior) rather than blocking the game:
 * this is a correctness improvement, not a hard dependency like the puzzle
 * JSON itself.
 */
export async function fetchForms(): Promise<FormMap> {
  try {
    const response = await fetch("/puzzles/forms.json");
    if (!response.ok) return {};
    return (await response.json()) as FormMap;
  } catch {
    return {};
  }
}

/** The key to use for rank lookup and duplicate detection: the mapped lemma
 *  if this surface form has one, otherwise the surface form itself
 *  (already-lemma guesses, and anything forms.json doesn't cover). */
export function resolveGuessKey(normalizedWord: string, forms: FormMap): string {
  return forms[normalizedWord] ?? normalizedWord;
}
